<?php 
    require_once('functions/function.php');
    getheader();
    getTopbar();
    getNavbar();
    getCarousel();
    getCounter();
    getAbout();
    getService();
    getFeature();
    getProject();
    getQuote();
    getTeam();
    getTestimonial();
    getfooter();
